app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.SearchPostsView.as_view(), name='search_results'),
    path('thanks', views.ThanksView.as_view(), name='thanks'),
    path('test', views.TestView.as_view(), name='test'),
    path('signup/', views.create_user, name='signup'),
    path('accounts/login/',
         auth_views.LoginView.as_view(template_name='app/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(),
         name='logout', kwargs={'next_page': '/'}),
    path('blog/<int:pk>/', views.BlogDetailView.as_view(), name='blog_detail'),
    path('blog/new/', views.create_blog, name='blog_new'),
    path('blog/<int:pk>/post/', views.add_post, name='post_new'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<int:pk>/edit/', views.UpdatePostView.as_view(), name='post_edit'),
    path('post/<int:pk>/remove/', views.DeletePostView.as_view(), name='post_remove'),
    path('post/<int:pk>/comments/',
         views.add_comment, name='post_comments'),
]

blogs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib import auth
from django.utils import timezone


class Blog(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    creator_photo = models.ImageField(upload_to='', default='user.png')
    title = models.CharField(max_length=100)
    description = models.TextField(default='')

    def __str__(self):
        return f'{self.title}'


class Post(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    intro = models.TextField(default='')
    text_content = models.TextField()
    image = models.ImageField(upload_to='', default='default-header.jpg')
    auth_required = models.BooleanField(default=False)
    published_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.blog}: {self.title}'


class Comment(models.Model):
    post = models.ForeignKey(
        Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text_content = models.TextField()
    published_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.post} {self.text_content}'

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, get_user_model
from captcha.fields import CaptchaField
from .models import Post, Blog, Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text_content',)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('blog', 'author', 'published_date')


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'creator_photo', 'description')


class UserForm(UserCreationForm):
    captcha = CaptchaField()

    class Meta():
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')

app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.views import generic
from django.utils import timezone
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from .models import Blog, Post, Comment
from django.contrib.auth.models import User
from .forms import PostForm, BlogForm, UserForm, CommentForm

# Create your views here.


def index(request):
    context = {'blog_list': Blog.objects.all()}
    return render(request, 'app/index.html', context=context)


@login_required
def add_post(request, pk):
    blog = get_object_or_404(Blog, pk=pk)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)

        if form.is_valid():
            post = form.save(commit=False)

            post.blog = blog
            post.author = blog.creator
            post.save()

            return redirect('blog_detail', pk=blog.pk)
    else:
        form = PostForm()

    return render(request, 'app/post_form.html', context={'form': form, 'author': blog.creator})


def create_user(request):
    if request.method == 'POST':
        form = UserForm(request.POST)

        if form.is_valid():
            user = form.save()
            # send_mail(
            #     'Welcome!',
            #     'Welcome to our fantastic Bloggers Community! We hope you will stay here for a while',
            #     'email host',
            #     [user.email, ],
            # )

            return redirect('login')
    else:
        form = UserForm()

    return render(request, 'app/signup.html', context={'form': form})


class BlogDetailView(generic.DetailView):
    model = Blog
    template_name = 'app/blog_detail.html'


@login_required
def create_blog(request):
    user = User.objects.get(pk=request.user.pk)

    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)

        if form.is_valid():
            blog = form.save(commit=False)

            blog.creator = user
            blog.save()

            return redirect('index')
    else:
        form = BlogForm()

    return render(request, 'app/blog_form.html', context={'form': form})


class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'app/post_detail.html'


class UpdatePostView(LoginRequiredMixin, generic.UpdateView):
    login_url = '/login/'
    model = Post
    form_class = PostForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse_lazy('post_detail', kwargs={'pk': self.kwargs.get('pk')})


class DeletePostView(LoginRequiredMixin, generic.DeleteView):
    login_url = '/login/'
    model = Post

    def get_success_url(self):
        post = super().get_object()
        return reverse_lazy('blog_detail', kwargs={'pk': post.blog.pk})


class SearchPostsView(generic.ListView):
    model = Post
    template_name = 'app/posts_search.html'

    def get_queryset(self):
        title = self.request.GET.get('title')
        blog = self.request.GET.get('blog')
        auth = self.request.GET.get('auth')

        objects = Post.objects.all()

        if blog == '':
            if auth == 'both':
                return Post.objects.filter(
                    title__icontains=title,
                )
            else:
                auth = auth == 'True'
                return Post.objects.filter(
                    title__icontains=title,
                    auth_required=auth
                )
        else:
            if auth == 'both':
                return Post.objects.filter(
                    title__icontains=title,
                    blog__id=blog,
                )
            else:
                auth = auth == 'True'
                return Post.objects.filter(
                    title__icontains=title,
                    blog__id=blog,
                    auth_required=auth
                )


@login_required
def add_comment(request, pk):
    user = User.objects.get(pk=request.user.pk)
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)

            comment.post = post
            comment.author = user
            comment.save()

            return redirect('post_detail', pk=pk)
    else:
        form = CommentForm()

    return render(request, 'app/post_comments.html', {'object': post, 'form': form})


class ThanksView(generic.TemplateView):
    template_name = 'app/thanks.html'


class TestView(generic.TemplateView):
    template_name = 'app/test.html'

app/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <div class="wrapper">
        <nav class="nav">
            <ul class="nav__list">
                <li class="nav__item">
                    <a class="nav__link" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav__item">
                    <a class="nav__link" href="#">Community</a>
                </li>
                <li class="nav__item">
                    <a class="nav__link" href="#">About</a>
                </li>
                <li class="nav__item">
                    {% if user.is_authenticated %}
                    <a class="nav__link" href="{% url 'logout' %}">Log out</a>
                    {% else %}
                    <a class="nav__link" href="{% url 'login' %}">Log in</a>
                    {% endif %}
                </li>
                <li class="nav__item">
                    {% if user.is_authenticated %}
                    <a class="nav__link" href="">
                        <i class="fa fa-user-circle" aria-hidden="true"></i>
                        <span class="username">{{ user }}</span>
                    </a>
                    {% else %}
                    <a class="nav__link" href="{% url 'signup' %}">Sign in</a>
                    {% endif %}
                </li>
            </ul>
        </nav>

        <header>
            <div class="welcome">
                <h1 class="welcome__title">Bloggers Community</h1>
                <h2 class="welcome__subtitle">The best site for novice bloggers</h2>
                <a class="welcome__link" href="{% url 'blog_new' %}">Start a blog!</a>
            </div>
        </header>

        <main>
            {% block content %}{% endblock %}
        </main>

        <footer>Copyright &copy; J&P 2020 all rights reserved</footer>
    </div>
</body>

</html>

app/templates/app/blog_detail.html
{% extends '_base.html' %}

{% load static %}
{% block title %}{{ object.title }}{% endblock %}

{% block content %}

<section class="detail">
    <h2 class="detail__title"><strong class="detail__welcome">Welcome to</strong>{{ object.title }} blog!</h2>
    <div class="detail__intro">
        <p class="detail__intro-desc">{{ object.description }}</p>
        <div class="detail__intro-info">
            <img class="detail__intro-logo" src="{{ object.creator_photo.url }}" alt="author">
            <span class="detail__intro-posts">
                Posts
                <span class="detail__intro-count">{{ object.post_set.count }}</span>
            </span>
            <span class="detail__author">
                Creator
                <span class="detail__author-name">{{ object.creator }}</span>
            </span>
        </div>
    </div>

    <div class="posts">
        <h3 class="posts__header">My posts</h3>
        {% if object.post_set.count %}

        {% for post in object.post_set.all %}

        {% if user.is_authenticated %}
        <article class="post">
            <div class="post__header">
                <img class="post__image" src="{{ post.image.url }}" alt="post header">
            </div>
            <h4 class="post__title">{{ post.title }}</h4>
            <span class="created">{{ post.published_date }}</span>
            <p class="post__intro">{{ post.intro }}</p>
            <a class="button" href="{% url 'post_detail' pk=post.pk %}">View more</a>
        </article>
        {% else %}

        {% if not post.auth_required %}
        <article class="post">
            <div class="post__header">
                <img class="post__image" src="{{ post.image.url }}" alt="post header">
            </div>
            <h4 class="post__title">{{ post.title }}</h4>
            <span class="created">{{ post.published_date }}</span>
            <p class="post__intro">{{ post.intro }}</p>
            <a class="button" href="{% url 'post_detail' pk=post.pk %}">View more</a>
        </article>
        {% else %}
        <p class="info info--post">Only logged members can see post: {{ post.title }}</p>
        {% endif %}

        {% endif %}

        {% endfor %}

        {% else %}

        <p class="info">Currently, there are no posts created yet</p>
        {% endif %}

        {% if user == object.creator %}
        <a class="button post__button" href="{% url 'post_new' pk=object.pk %}">New Post</a>
        {% endif %}
    </div>
</section>

{% endblock %}

app/templates/app/blog_form.html
{% extends '_base.html' %}

{% block title %} Create Blog {% endblock %}

{% block content %}

{% if user.is_authenticated %}
<div class="form-wrapper">
    <h2 class="form__header">Create Blog</h2>
    <form class="form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button" type="submit">Send</button>
    </form>
</div>
{% else %}
<p class="info">You have to be a member to create a Blog</p>
{% endif %}

{% endblock %}

app/templates/app/index.html
{% extends '_base.html' %}

{% block title %}Homepage{% endblock %}

{% block content %}
<section class="blogs">
    <h2 class="blogs__header">Check out our blogs</h2>

    <div class="search">
        <form action="{% url 'search_results' %}" method="GET">
            <input name="title" type="text" placeholder="Post title">
            <select name="blog" id="blog-select">
                <option value="">Choose blog</option>
                {% for blog in blog_list %}
                <option value="{{ blog.id }}">{{ blog.title }}</option>
                {% endfor %}
            </select>
            <select name="auth" id="auth-select">
                <option value="both">Both</option>
                <option value="False">Public</option>
                <option value="True">Private</option>
            </select>
            <button class="button search__button" type="submit">Search</button>
        </form>
    </div>

    {% if blog_list %}
    <div class="blog-list">
        {% for blog in blog_list %}
        <div class="blog">
            <h2 class="blog__title">{{ blog.title }}</h2>
            <div class="blog__text">
                <p class="blog__description">{{ blog.description }}</p>
                <div class="blog__info">
                    <a href="{% url 'blog_detail' pk=blog.pk %}" class="button">View</a>
                    <span class="blog__author">created by: {{ blog.creator.username }}</span>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    {% else %}
    <p class="info">There are currently no blogs started :(</>
    {% endif %}
    </section>
{% endblock %}

app/templates/app/login.html
{% extends '_base.html' %}

{% block title %} Log in {% endblock %}


{% block content %}

<div class="form-wrapper form-wrapper--login">
    <h2 class="form__header">Please log in</h2>

    {% if form.errors %}
    <p class="error">Your username and password didn't match. Please try again</p>
    {% endif %}

    {% if user.is_authenticated %}
    <p class="info">You are already logged in</p>
    {% else %}
    <form class="form" action="{% url 'login' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button" type="submit">Login</button>
    </form>
    {% endif %}
</div>

{% endblock %}

app/templates/app/post_comments.html
{% extends '_base.html' %}
{% load static %}

{% block title %} Post comments {% endblock %}

{% block content %}

<section class="comments">
    <h2 class="comments__header">There {% if object.comments.count == 1 %}is {% else %}are
        {% endif %}{{ object.comments.count }} comment{% if object.comments.count != 1 %}s{% endif %}</h2>

    {% if object.comments.count %}

    {% for comment in object.comments.all %}

    <div class="comment">
        <img class="comment__avatar" src="{% static 'app/img/user.png' %}" alt="comment author">
        <div class="comment__content">
            <span class="comment__author">{{ comment.author.username }}</span>
            <span class="created comment__date">{{ comment.published_date }}</span>
            <p class="comment__text">{{ comment.text_content }}</p>
        </div>
    </div>

    {% endfor %}

    {% else %}
    <p class="info">There are no comments yet, be first to comment!</p>
    {% endif %}

    <div class="form-wrapper form-wrapper--comments">
        <h3 class="form__header form__header--comments">Leave a comment</h3>
        <form class="form" action="{% url 'post_comments' pk=object.pk %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button" type="submit">Send</button>
        </form>
    </div>

    <a class="button comments__button" href="{% url 'post_detail' pk=object.pk %}">Go back</a>
</section>

{% endblock %}

app/templates/app/post_confirm_delete.html
{% extends '_base.html' %}

{% block title %} Delete Post {% endblock %}

{% block content %}

<form class="form form--delete" method="POST">
    {% csrf_token %}
    <p class="form__header form__header--delete">Are you sure you want to delete this post?</p>
    <button class="button button--delete" type="submit">Confirm</button>
    <a class="button" href="{% url 'post_detail' pk=post.pk %}">Cancel</a>
</form>

{% endblock %}

app/templates/app/post_detail.html
{% extends '_base.html' %}

{% block title %} {{ object.title }} {% endblock %}

{% block content %}

{% if not user.is_authenticated and object.auth_required %}
<p class="info">You have to be a Member to see this Post</p>
{% else %}
<section class="from">
    <span class="from__content">{{ object.blog }} → {{ object.title }}</span>

    <article class="post post--full">
        <div class="post__hero">
            <img class="post__image" src="{{ object.image.url }}" alt="post header">
        </div>
        <h4 class="post__title post__title--full">{{ object.title }}</h4>
        <span class="created">{{ object.published_date }}</span>
        <p class="post__text">{{ object.text_content }}</p>
        <div class="post__options">
            {% if user == object.author %}
            <a class="button" href="{% url 'post_edit' pk=object.pk %}">Edit</a>
            <a class="button post__remove" href="{% url 'post_remove' pk=object.pk %}">Remove</a>
            {% endif %}
        </div>
        <a class="button" href="{% url 'post_comments' pk=object.pk %}">View comments ({{ object.comments.count }})</a>
        <a class="button post__back" href="{% url 'blog_detail' pk=object.blog.pk %}">Go back</a>
    </article>
</section>
{% endif %}

{% endblock %}

app/templates/app/post_form.html
{% extends '_base.html' %}

{% block title %} Create Post {% endblock %}

{% block content %}

{% if user.username == author.username  %}
<div class="form-wrapper">
    <h2 class="form__header">Create Post</h2>
    <form class="form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button" type="submit">Send</button>
    </form>
</div>
{% else %}
<p class="info">Only Blog creator can add posts</p>
{% endif %}

{% endblock %}

app/templates/app/post_update_form.html
{% extends '_base.html' %}

{% block title %} Create Post {% endblock %}

{% block content %}

{% if object.author == user  %}
<div class="form-wrapper">
    <h2 class="form__header">Edit Post</h2>
    <form class="form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button" type="submit">Send</button>
    </form>
</div>
{% else %}
<p class="info">Only Blog creator can edit posts</p>
{% endif %}

{% endblock %}

app/templates/app/posts_search.html
{% extends '_base.html' %}

{% block title %} Search results {% endblock %}

{% block content %}
<div class="posts posts--search">
    <h3 class="posts__header">Search results</h3>
    {% if object_list.count %}

    {% for post in object_list %}

    {% if user.is_authenticated %}
    <article class="post">
        <div class="post__header">
            <img class="post__image" src="{{ post.image.url }}" alt="post header">
        </div>
        <h4 class="post__title">{{ post.title }}</h4>
        <span class="created">{{ post.published_date }}</span>
        <p class="post__intro">{{ post.intro }}</p>
        <a class="button" href="{% url 'post_detail' pk=post.pk %}">View more</a>
    </article>
    {% else %}

    {% if not post.auth_required %}
    <article class="post">
        <div class="post__header">
            <img class="post__image" src="{{ post.image.url }}" alt="post header">
        </div>
        <h4 class="post__title">{{ post.title }}</h4>
        <span class="created">{{ post.published_date }}</span>
        <p class="post__intro">{{ post.intro }}</p>
        <a class="button" href="{% url 'post_detail' pk=post.pk %}">View more</a>
    </article>
    {% else %}
    <p class="info info--post">Only logged members can see post: {{ post.title }}</p>
    {% endif %}

    {% endif %}

    {% endfor %}

    {% else %}

    <p class="info">No matches found, please try again</p>
    {% endif %}
</div>
{% endblock %}

app/templates/app/signup.html
{% extends '_base.html' %}

{% block title %} Sign up {% endblock %}

{% block content %}

<div class="form-wrapper">
    <h2 class="form__header">Register here</h2>

    {% if user.is_authenticated %}
    <p class="info">You are already a member</p>
    {% else %}
    <form class="form" action="{% url 'signup' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button" type="submit">Sign in</button>
    </form>
    {% endif %}
</div>

{% endblock %}

app/templates/app/test.html
{% extends '_base.html' %}

{% block title %} Successful Logout {% endblock %}

{% block content %}

<h2 class="info">Welcome back {{ user }}!</h2>

{% endblock %}

app/templates/app/thanks.html
{% extends '_base.html' %}

{% block title %} Successful Logout {% endblock %}

{% block content %}

<h2 class="info">Thanks for visiting, come back soon!</h2>

{% endblock %}

app/templates/post_detail.html
{% extends '_base.html' %}

{% block title %} {{ object.title }} {% endblock %}

{% block content %}

{% if not user.is_authenticated and object.auth_required %}
<p class="info">You have to be a Member to see this Post</p>
{% else %}
<section class="from">
    <span class="from__content">{{ object.blog }} → {{ object.title }}</span>

    <article class="post post--full">
        <div class="post__hero">
            <img class="post__image" src="{{ object.image.url }}" alt="post header">
        </div>
        <h4 class="post__title post__title--full">{{ object.title }}</h4>
        <span class="created">{{ object.published_date }}</span>
        <p class="post__text">{{ object.text_content }}</p>
        <div class="post__options">
            <a class="button" href="{% url 'post_edit' pk=object.pk %}">Edit</a>
            <!-- <a class="button" href="{% url 'post_comments' pk=object.pk %}">Remove</a> -->
        </div>
        <a class="button" href="{% url 'post_comments' pk=object.pk %}">View comments ({{ object.comments.count }})</a>
        <a class="button post__back" href="{% url 'blog_detail' pk=object.blog.pk %}">Go back</a>
    </article>
</section>
{% endif %}

{% endblock %}